/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.GorjTable.telas;

/**
 *
 * @author Jarvis
 */
import java.sql.*;
import br.com.GorjTable.dal.ConnectionModule;
import static br.com.GorjTable.dal.ConnectionModule.conector;
import javax.swing.JOptionPane;

public class CadastroClientes extends javax.swing.JInternalFrame {

    Connection conexao = null;

    public CadastroClientes() {
        initComponents();
        conexao = ConnectionModule.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_cad = new javax.swing.JLabel();
        Nome_cad = new javax.swing.JLabel();
        Comercio_cad = new javax.swing.JLabel();
        Cidade_cad = new javax.swing.JLabel();
        Endereço_cad = new javax.swing.JLabel();
        CNPJ_cad = new javax.swing.JLabel();
        Status_cad = new javax.swing.JLabel();
        Telefone_cad = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_Nome = new javax.swing.JTextField();
        txt_Comercio = new javax.swing.JTextField();
        txt_Cidade = new javax.swing.JTextField();
        txt_Endereço = new javax.swing.JTextField();
        txt_CNPJ = new javax.swing.JTextField();
        txt_Telefone = new javax.swing.JTextField();
        combo_Status = new javax.swing.JComboBox<>();
        btn_cad = new javax.swing.JButton();
        btn_alt = new javax.swing.JButton();
        btn_excl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SearchBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Clientes");

        ID_cad.setText("ID");

        Nome_cad.setText("Nome");

        Comercio_cad.setText("Comercio");

        Cidade_cad.setText("Cidade");

        Endereço_cad.setText("Endereço");

        CNPJ_cad.setText("CNPJ");

        Status_cad.setText("Status");

        Telefone_cad.setText("Telefone");

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        txt_Comercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ComercioActionPerformed(evt);
            }
        });

        txt_Endereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EndereçoActionPerformed(evt);
            }
        });

        combo_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Sem Interesse", "Com Interesse", "Já Negociado", " " }));

        btn_cad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/GorjTable/icons/create.png"))); // NOI18N
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        btn_alt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/GorjTable/icons/update.png"))); // NOI18N
        btn_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altActionPerformed(evt);
            }
        });

        btn_excl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/GorjTable/icons/delete.png"))); // NOI18N
        btn_excl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exclActionPerformed(evt);
            }
        });

        jLabel1.setText("ADD");

        jLabel2.setText("UPDATE");

        jLabel3.setText("DELETE");

        SearchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/GorjTable/icons/Search.png"))); // NOI18N
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        jLabel4.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefone_cad)
                            .addComponent(Nome_cad)
                            .addComponent(ID_cad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Comercio_cad)
                                        .addComponent(Cidade_cad))
                                    .addComponent(Endereço_cad)
                                    .addComponent(CNPJ_cad, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Status_cad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Comercio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SearchBTN)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_alt)
                                        .addComponent(btn_excl)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))))
                                    .addGap(84, 84, 84))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_cad)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(113, 113, 113))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_cad)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome_cad)
                            .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telefone_cad)
                            .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_alt)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Comercio_cad)
                                .addComponent(txt_Comercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cidade_cad)
                            .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Endereço_cad)
                            .addComponent(txt_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_excl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNPJ_cad)
                    .addComponent(txt_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(SearchBTN)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status_cad)
                    .addComponent(combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1016, 802);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        // TODO add your handling code here:
        adcionarCL();
    }//GEN-LAST:event_btn_cadActionPerformed

    private void txt_ComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComercioActionPerformed

    private void txt_EndereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EndereçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EndereçoActionPerformed

    private void btn_exclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exclActionPerformed

        Remove();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exclActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        Consultar();

    }//GEN-LAST:event_SearchBTNActionPerformed

    private void btn_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altActionPerformed
        Update();
    }//GEN-LAST:event_btn_altActionPerformed

    private void adcionarCL() {
        String sql = "INSERT INTO clientesgorj(Id, nome, comercio, cidade, endereco, cnpj, status_cl, telefone) VALUES(?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement pst = conector().prepareStatement(sql);
            pst.setString(1, txt_ID.getText());
            pst.setString(2, txt_Nome.getText());
            pst.setString(8, txt_Telefone.getText());
            pst.setString(3, txt_Comercio.getText());
            pst.setString(4, txt_Cidade.getText());
            pst.setString(5, txt_Endereço.getText());
            pst.setString(6, txt_CNPJ.getText());
            pst.setString(7, combo_Status.getSelectedItem().toString());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Cliente Cadastrado com Sucesso!!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void Remove() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Remover este Cliente ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM clientesgorj WHERE id=?";
            try {
                PreparedStatement stmt = ConnectionModule.conector().prepareStatement(sql);
                stmt.setString(1, txt_ID.getText());
                int apagado = stmt.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario Removido Com sucesso");
                    txt_ID.setText(null);
                    txt_Nome.setText(null);
                    txt_Comercio.setText(null);
                    txt_Cidade.setText(null);
                    txt_Endereço.setText(null);
                    txt_CNPJ.setText(null);
                    combo_Status.setSelectedItem(null);
                    txt_Telefone.setText(null);
                    //id(int PK), nome, comercio, cidade, endereco, cnpj status_cl, telefone
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    private void Consultar() {
        String sql = "SELECT*FROM clientesgorj WHERE Id=?";
        try {
            PreparedStatement stmt = ConnectionModule.conector().prepareStatement(sql);
            stmt.setString(1, txt_ID.getText());
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                txt_Nome.setText(rs.getString(2));
                txt_Comercio.setText(rs.getString(3));
                txt_Cidade.setText(rs.getString(4));
                txt_Endereço.setText(rs.getString(5));
                txt_CNPJ.setText(rs.getString(6));
                txt_Telefone.setText(rs.getString(8));
                combo_Status.setSelectedItem(rs.getString(7));
                //id(int PK), nome, comercio, cidade, endereco, cnpj status_cl, telefone 

            } else {
                JOptionPane.showMessageDialog(null, "Usuario Não Cadastrado");
                txt_ID.setText(null);
                txt_Nome.setText(null);
                txt_Comercio.setText(null);
                txt_Cidade.setText(null);
                txt_Endereço.setText(null);
                txt_CNPJ.setText(null);
                combo_Status.setSelectedItem(null);
                txt_Telefone.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void Update() {
        String sql = "UPDATE  clientesgorj SET nome=?, comercio=?, cidade=?, endereco=?, cnpj=?, status_cl=?, telefone=? WHERE Id=?";

        try {
            PreparedStatement stmt = ConnectionModule.conector().prepareStatement(sql);
            stmt.setString(1, txt_Nome.getText()); //1
            stmt.setString(2, txt_Comercio.getText()); //2
            stmt.setString(3, txt_Cidade.getText()); //3
            stmt.setString(4, txt_Endereço.getText()); //4
            stmt.setString(5, txt_CNPJ.getText()); //5
            stmt.setString(6, combo_Status.getSelectedItem().toString()); //6
            stmt.setString(7, txt_Telefone.getText()); //7
            stmt.setString(8, txt_ID.getText());

            if (((txt_ID.getText().isEmpty() || txt_Nome.getText().isEmpty() || txt_Comercio.getText().isEmpty()))) {
                JOptionPane.showMessageDialog(null, "Preencha todos os Campos");
            } else {

                int updt = stmt.executeUpdate();

                if (updt > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario alterado com Sucesso");
                    txt_ID.setText(null);
                    txt_Nome.setText(null);
                    txt_Comercio.setText(null);
                    txt_Cidade.setText(null);
                    txt_Endereço.setText(null);
                    txt_CNPJ.setText(null);
                    combo_Status.setSelectedItem(null);
                    txt_Telefone.setText(null);
                } else {

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        //id(int PK), nome, comercio, cidade, endereco, cnpj status_cl, telefone 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CNPJ_cad;
    private javax.swing.JLabel Cidade_cad;
    private javax.swing.JLabel Comercio_cad;
    private javax.swing.JLabel Endereço_cad;
    private javax.swing.JLabel ID_cad;
    private javax.swing.JLabel Nome_cad;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JLabel Status_cad;
    private javax.swing.JLabel Telefone_cad;
    private javax.swing.JButton btn_alt;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_excl;
    private javax.swing.JComboBox<String> combo_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_CNPJ;
    private javax.swing.JTextField txt_Cidade;
    private javax.swing.JTextField txt_Comercio;
    private javax.swing.JTextField txt_Endereço;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Telefone;
    // End of variables declaration//GEN-END:variables
}
