/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.GorjTable.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Jarvis
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaDeTrabApp = new javax.swing.JDesktopPane();
        LOGO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnPesquisa = new javax.swing.JMenu();
        Pesq_Todos = new javax.swing.JMenuItem();
        mnAju = new javax.swing.JMenu();
        sobreBTN = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        KITAR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela Gorj");
        setResizable(false);

        AreaDeTrabApp.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout AreaDeTrabAppLayout = new javax.swing.GroupLayout(AreaDeTrabApp);
        AreaDeTrabApp.setLayout(AreaDeTrabAppLayout);
        AreaDeTrabAppLayout.setHorizontalGroup(
            AreaDeTrabAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        AreaDeTrabAppLayout.setVerticalGroup(
            AreaDeTrabAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/GorjTable/icons/logo_1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel1.setText("        Juninho INC ");

        MenuBar.setBackground(new java.awt.Color(255, 102, 204));

        mnCadastro.setText("Cadastro");
        mnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnCadastro.add(jMenuItem1);

        MenuBar.add(mnCadastro);

        mnPesquisa.setText("Pesquisa");

        Pesq_Todos.setText("Todos");
        Pesq_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesq_TodosActionPerformed(evt);
            }
        });
        mnPesquisa.add(Pesq_Todos);

        MenuBar.add(mnPesquisa);

        mnAju.setText("Ajuda");

        sobreBTN.setText("Sobre");
        sobreBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreBTNActionPerformed(evt);
            }
        });
        mnAju.add(sobreBTN);

        MenuBar.add(mnAju);

        jMenu4.setText("Config's");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        KITAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        KITAR.setText("KITAR");
        KITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KITARActionPerformed(evt);
            }
        });
        jMenu4.add(KITAR);

        MenuBar.add(jMenu4);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AreaDeTrabApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGO, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LOGO)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 432, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(AreaDeTrabApp)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1291, 847));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void KITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KITARActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Puxar o cabo ??", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_KITARActionPerformed

    private void mnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroActionPerformed

    }//GEN-LAST:event_mnCadastroActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroClientes clientes = new CadastroClientes();
        clientes.setVisible(true);
        AreaDeTrabApp.add(clientes);
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    private void Pesq_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesq_TodosActionPerformed
        TabelaDeClientes table = new TabelaDeClientes();
        table.setVisible(true);
        dispose();


    }//GEN-LAST:event_Pesq_TodosActionPerformed

    private void sobreBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreBTNActionPerformed
       Sobre sobre = new Sobre();
       sobre.setVisible(true);
       AreaDeTrabApp.add(sobre);
       
    }//GEN-LAST:event_sobreBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaDeTrabApp;
    private javax.swing.JMenuItem KITAR;
    private javax.swing.JLabel LOGO;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem Pesq_Todos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnAju;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnPesquisa;
    private javax.swing.JMenuItem sobreBTN;
    // End of variables declaration//GEN-END:variables
}
